language: python
dist: trusty

services:
  - docker

before_install:
  - docker build --rm -t jumpscale .

script:
  - docker run --rm -t jumpscale /bin/bash -c "source /sandbox/env.sh; kosmos --instruct /sandbox/nacl_config.toml; python3 -m pytest -v /sandbox/code/github/threefoldtech/jumpscaleX --ignore=/sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/data/schema/"
  - docker run --rm -t jumpscale /bin/bash -c "source /sandbox/env.sh;  kosmos --instruct /sandbox/nacl_config.toml; python3 -m pytest -v /sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/data/schema/"

after_success:
  - docker run --rm -t jumpscale /bin/bash -c "codecov"